"""BN à partir des exports SCGM : agrégation, structure, apprentissage."""

from .aggregate_bn_variables import (
    create_accident_matrix_from_macro_transfer,
    create_accident_topic_matrix,
    export_aggregate_outputs,
)
from .bn_diagnostics import compare_structure_rows, run_model_diagnostics
from .bn_inference import run_bn_queries
from .bn_learning import export_cpds_to_dir, fit_bn_parameters, save_bn_pickle, try_write_bif
from .bn_structure import (
    MACRO_ONTOLOGY_FR,
    export_edge_tables,
    ensure_inter_macro_chain_edges,
    learn_macro_constrained_structure,
    learn_unconstrained_structure,
    macro_chain_model,
    standard_macro_edge_templates,
)
from .bn_paths import enumerate_macro_paths, extract_bn_path_scenarios
from .bn_visualization import (
    build_node_cards_for_model,
    build_node_short_title,
    build_node_summary_label,
    build_short_title_map,
    build_topic_node_label_map,
    extract_subgraph_for_slide,
    join_theme_summary_to_selected_variables,
    load_openai_themes_for_bn,
    path_nodes_from_scenario_row,
    plot_bn_scenario_slide,
    resolve_openai_themes_path,
    cpd_binary_marginal,
    display_node_card,
    export_node_cards_png,
    export_node_marginals_csv,
    format_node_card,
    format_prob_bar,
    plot_adjacency_heatmap,
    plot_bn_graph,
    plot_bn_graph_cpd_boxes,
    plot_macro_causality_schematic,
    try_plotly_interactive,
    try_pyvis_bn_graph,
)
from .scenario_interpretation import (
    build_configuration_probable,
    build_topic_variable_label_map,
    enrich_scenarios_table,
    export_scenario_interpretations,
)
from .scenario_mining import export_scenarios, extract_typical_scenarios
from .utils import (
    ensure_output_dirs,
    find_repo_root,
    load_metadata_for_bn,
    require_bn_export_files,
    resolve_repo_path,
)

__all__ = [
    "require_bn_export_files",
    "load_metadata_for_bn",
    "find_repo_root",
    "resolve_repo_path",
    "ensure_output_dirs",
    "create_accident_topic_matrix",
    "create_accident_matrix_from_macro_transfer",
    "export_aggregate_outputs",
    "learn_macro_constrained_structure",
    "learn_unconstrained_structure",
    "macro_chain_model",
    "export_edge_tables",
    "ensure_inter_macro_chain_edges",
    "fit_bn_parameters",
    "save_bn_pickle",
    "export_cpds_to_dir",
    "try_write_bif",
    "run_bn_queries",
    "plot_bn_graph",
    "plot_bn_graph_cpd_boxes",
    "plot_macro_causality_schematic",
    "MACRO_ONTOLOGY_FR",
    "standard_macro_edge_templates",
    "build_topic_node_label_map",
    "build_node_short_title",
    "build_node_summary_label",
    "build_short_title_map",
    "build_node_cards_for_model",
    "cpd_binary_marginal",
    "format_prob_bar",
    "format_node_card",
    "display_node_card",
    "export_node_marginals_csv",
    "export_node_cards_png",
    "plot_adjacency_heatmap",
    "try_plotly_interactive",
    "try_pyvis_bn_graph",
    "load_openai_themes_for_bn",
    "resolve_openai_themes_path",
    "join_theme_summary_to_selected_variables",
    "extract_typical_scenarios",
    "enumerate_macro_paths",
    "extract_bn_path_scenarios",
    "extract_subgraph_for_slide",
    "path_nodes_from_scenario_row",
    "plot_bn_scenario_slide",
    "export_scenarios",
    "build_topic_variable_label_map",
    "build_configuration_probable",
    "enrich_scenarios_table",
    "export_scenario_interpretations",
    "run_model_diagnostics",
    "compare_structure_rows",
]
